In [1]:
import numpy as np
import pandas as pd

In [2]:
array = np.arange(10)
df = pd.DataFrame(array)

In [3]:
pick = np.random.permutation(len(array))[:3]
pick

array([4, 1, 3])

In [4]:
array[pick]

array([4, 1, 3])

In [5]:
array.take(pick)

array([4, 1, 3])

In [6]:
df.iloc[pick]

0
4  4
1  1
3  3

In [7]:
df.take(pick)

0
4  4
1  1
3  3

In [8]:
np.random.seed(42)
pick = np.random.permutation(len(array))[:3]
pick

array([8, 1, 5])