In [1]:
import numpy as np

In [4]:
arr1 = np.array([1, 3, 5, 7, 9])
arr1

array([1, 3, 5, 7, 9])

In [5]:
arr2 = np.array([
    [1, 2, 3],
    [10, 20, 30]
])
arr2

array([[ 1,  2,  3],
       [10, 20, 30]])

In [8]:
arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [10, 20, 30],
        [40, 50, 60],
    ],
])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [9]:
arr3.dtype

dtype('int32')

In [10]:
arr3.shape

(2, 2, 3)

In [11]:
arr3.strides

(24, 12, 4)

In [12]:
arr2[1,1] = 999
arr2

array([[  1,   2,   3],
       [ 10, 999,  30]])

In [15]:
arr2[:, 2:] = [[100], [200]]
arr2

array([[  1,   2, 100],
       [ 10, 999, 200]])

In [17]:
arr2[1,:].sort()
arr2

array([[  1,   2, 100],
       [ 10, 200, 999]])

In [20]:
arr2[:, ::-1][0][0] = -100
arr2

array([[   1,    2, -100],
       [  10,  200,  999]])