In [1]:
import numpy as np

In [5]:
arr1 = np.array(range(0, 10), dtype=np.float64).reshape(2, 5)
arr1

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [6]:
arr2 = np.ones_like(arr1)
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
arr3 = np.arange(10, dtype=np.float64).reshape(2, 5)
arr3

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [13]:
%timeit np.array(range(0, 10000), dtype=np.float64)

1.45 ms ± 10.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
%timeit np.arange(10000, dtype=np.float64)

8.52 µs ± 85 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
