In [1]:
import numpy as np

In [2]:
arr1 = np.arange(10, dtype=np.float32)
arr2 = np.arange(10, dtype=np.int32)
arr1 + arr2

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [3]:
(arr1 + arr2).dtype

dtype('float64')

In [4]:
(arr1 + arr2).astype(np.int32)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr3 = np.array(['1.2', '3', '0.9', '-5'])
arr3.dtype

dtype('<U3')

In [7]:
arr3.astype(np.float32)

array([ 1.2,  3. ,  0.9, -5. ], dtype=float32)