In [1]:
import numpy as np

In [2]:
arr1 = np.arange(8).reshape(2, 2, 2)
arr2 = np.random.rand(2, 2, 2)

In [3]:
arr1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [4]:
arr2

array([[[0.51797132, 0.20327664],
        [0.86437203, 0.55056861]],

       [[0.34470659, 0.10401953],
        [0.83783542, 0.89768511]]])

In [5]:
arr1 + arr2

array([[[0.51797132, 1.20327664],
        [2.86437203, 3.55056861]],

       [[4.34470659, 5.10401953],
        [6.83783542, 7.89768511]]])

In [6]:
arr1 * arr2

array([[[0.        , 0.20327664],
        [1.72874407, 1.65170583]],

       [[1.37882638, 0.52009765],
        [5.02701254, 6.28379577]]])

In [7]:
arr1 * 100 + arr2 * 10

array([[[  5.17971317, 102.03276638],
        [208.64372035, 305.5056861 ]],

       [[403.44706595, 501.04019529],
        [608.37835424, 708.9768511 ]]])

In [8]:
arr1 * 100

array([[[  0, 100],
        [200, 300]],

       [[400, 500],
        [600, 700]]])

In [12]:
def loop_double(arr):
    n, m = arr.shape
    for i in range(n):
        for j in range(m):
            arr[i][j] *= 2
    return arr
loop_double(np.arange(9).reshape(3, 3))

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [13]:
%timeit loop_double(np.arange(10000).reshape(100, 100))

6.4 ms ± 66.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
%timeit np.arange(10000).reshape(100, 100) * 2

14.9 µs ± 252 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
