In [1]:
import numpy as np

In [2]:
arr1 = np.arange(8).reshape(2, 2, 2)
arr2 = np.random.rand(2, 2, 2)

In [3]:
arr1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [4]:
arr2

array([[[0.28718568, 0.46697359],
        [0.56791058, 0.72510447]],

       [[0.03667108, 0.90077012],
        [0.94011437, 0.95437399]]])

In [5]:
arr1 + arr2

array([[[0.28718568, 1.46697359],
        [2.56791058, 3.72510447]],

       [[4.03667108, 5.90077012],
        [6.94011437, 7.95437399]]])

In [6]:
arr1 * arr2

array([[[0.        , 0.46697359],
        [1.13582116, 2.1753134 ]],

       [[0.14668434, 4.50385059],
        [5.64068621, 6.68061796]]])

In [7]:
arr1 * 100 + arr2 * 10

array([[[  2.87185675, 104.66973588],
        [205.67910579, 307.25104467]],

       [[400.36671085, 509.00770118],
        [609.40114368, 709.54373994]]])

In [8]:
arr1 * 100

array([[[  0, 100],
        [200, 300]],

       [[400, 500],
        [600, 700]]])

In [9]:
def loop_double(arr):
    n, m = arr.shape
    for i in range(n):
        for j in range(m):
            arr[i][j] *= 2
    return arr
loop_double(np.arange(9).reshape(3, 3))

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [10]:
%timeit loop_double(np.arange(10000).reshape(100, 100))

5.61 ms ± 203 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit np.arange(10000).reshape(100, 100) * 2

12.9 µs ± 307 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
arr3 = np.arange(8*5*3).reshape(8, 5, 3)

In [17]:
np.sum(arr3)

7140

In [18]:
np.sum(arr3, axis=0)

array([[420, 428, 436],
       [444, 452, 460],
       [468, 476, 484],
       [492, 500, 508],
       [516, 524, 532]])

In [22]:
np.sum(arr3, axis=1)

array([[ 30,  35,  40],
       [105, 110, 115],
       [180, 185, 190],
       [255, 260, 265],
       [330, 335, 340],
       [405, 410, 415],
       [480, 485, 490],
       [555, 560, 565]])

In [23]:
np.sum(arr3, axis=2)

array([[  3,  12,  21,  30,  39],
       [ 48,  57,  66,  75,  84],
       [ 93, 102, 111, 120, 129],
       [138, 147, 156, 165, 174],
       [183, 192, 201, 210, 219],
       [228, 237, 246, 255, 264],
       [273, 282, 291, 300, 309],
       [318, 327, 336, 345, 354]])

In [24]:
np.sum(arr3, axis=2, keepdims=1)

array([[[  3],
        [ 12],
        [ 21],
        [ 30],
        [ 39]],

       [[ 48],
        [ 57],
        [ 66],
        [ 75],
        [ 84]],

       [[ 93],
        [102],
        [111],
        [120],
        [129]],

       [[138],
        [147],
        [156],
        [165],
        [174]],

       [[183],
        [192],
        [201],
        [210],
        [219]],

       [[228],
        [237],
        [246],
        [255],
        [264]],

       [[273],
        [282],
        [291],
        [300],
        [309]],

       [[318],
        [327],
        [336],
        [345],
        [354]]])