In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.array([
    [-1.734464, 1.246888, 0.921260, -0.893499],
    [0.954527, -0.573931, -0.893817, 1.563767],
    [0.713028, -0.259905, -3.059838, -1.824971],
    [0.257634, 0.224982, 0.510233, 1.218742],
    [2.536384, 2.255618, -1.407619, 0.545119],
    [1.224132, 1.863338, 0.333345, -1.985052],
])
pd.DataFrame(arr)

0         1         2         3
0 -1.734464  1.246888  0.921260 -0.893499
1  0.954527 -0.573931 -0.893817  1.563767
2  0.713028 -0.259905 -3.059838 -1.824971
3  0.257634  0.224982  0.510233  1.218742
4  2.536384  2.255618 -1.407619  0.545119
5  1.224132  1.863338  0.333345 -1.985052

In [3]:
arr[1:3]

array([[ 0.954527, -0.573931, -0.893817,  1.563767],
       [ 0.713028, -0.259905, -3.059838, -1.824971]])

In [4]:
arr[:, 1:3]

array([[ 1.246888,  0.92126 ],
       [-0.573931, -0.893817],
       [-0.259905, -3.059838],
       [ 0.224982,  0.510233],
       [ 2.255618, -1.407619],
       [ 1.863338,  0.333345]])

In [5]:
arr[3:, :2]

array([[0.257634, 0.224982],
       [2.536384, 2.255618],
       [1.224132, 1.863338]])

### 使用布尔值选取

In [6]:
name = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])

In [7]:
data = np.arange(name.shape[0] * 5).reshape(name.shape[0], 5)

In [8]:
name, data

(array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4'),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]]))

In [9]:
name == 'bob'

array([ True, False, False,  True, False, False, False])

In [10]:
data[name == 'bob']

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [11]:
data[[True, False, False, True, False, False, False]]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

### 练习4：选出1、2列均大于0的行

In [15]:
arr = np.array([
    [-1.734464, 1.246888, 0.921260, -0.893499],
    [0.954527, -0.573931, -0.893817, 1.563767],
    [0.713028, -0.259905, -3.059838, -1.824971],
    [0.257634, 0.224982, 0.510233, 1.218742],
    [2.536384, 2.255618, -1.407619, 0.545119],
    [1.224132, 1.863338, 0.333345, -1.985052],
])
pd.DataFrame(arr)

0         1         2         3
0 -1.734464  1.246888  0.921260 -0.893499
1  0.954527 -0.573931 -0.893817  1.563767
2  0.713028 -0.259905 -3.059838 -1.824971
3  0.257634  0.224982  0.510233  1.218742
4  2.536384  2.255618 -1.407619  0.545119
5  1.224132  1.863338  0.333345 -1.985052

In [16]:
mask = (arr[:, 1:3] > 0)
mask

array([[ True,  True],
       [False, False],
       [False, False],
       [ True,  True],
       [ True, False],
       [ True,  True]])

In [17]:
mask[:, 0], mask[:, 1], mask[:, 0] & mask[:, 1]

(array([ True, False, False,  True,  True,  True]),
 array([ True, False, False,  True, False,  True]),
 array([ True, False, False,  True, False,  True]))

In [18]:
arr[mask[:, 0] & mask[:, 1]]

array([[-1.734464,  1.246888,  0.92126 , -0.893499],
       [ 0.257634,  0.224982,  0.510233,  1.218742],
       [ 1.224132,  1.863338,  0.333345, -1.985052]])