In [1]:
import numpy as np

In [2]:
x = np.arange(3 * 3).reshape(3, 3)
y = np.arange(3 * 3).reshape(3, 3) + 100
print(x)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[100 101 102]
 [103 104 105]
 [106 107 108]]


In [3]:
x * y

array([[  0, 101, 204],
       [309, 416, 525],
       [636, 749, 864]])

In [4]:
x.dot(y)

array([[ 315,  318,  321],
       [1242, 1254, 1266],
       [2169, 2190, 2211]])

In [6]:
mx = np.matrix(x)
my = np.matrix(y)
print(mx)
print(my)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[100 101 102]
 [103 104 105]
 [106 107 108]]


In [7]:
mx * my

matrix([[ 315,  318,  321],
        [1242, 1254, 1266],
        [2169, 2190, 2211]])

In [12]:
m = np.matrix([
    [1, 5, 7],
    [3, 13, 8],
    [5,  11, 9],
])
m.I

matrix([[-0.22307692, -0.24615385,  0.39230769],
        [-0.1       ,  0.2       , -0.1       ],
        [ 0.24615385, -0.10769231,  0.01538462]])

In [16]:
np.round(m.I * m, 10)

array([[ 1., -0., -0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])